export const LoginTypes = {
  GET_LOGIN_LOADING: "GET_LOGIN_LOADING",
  GET_LOGIN_SUCCESS: "GET_LOGIN_SUCCESS",
  GET_LOGIN_FAIL: "GET_LOGIN_FAIL",
  
  GET_MOVIES_LOADING: "GET_MOVIES_LOADING",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAIL: "GET_MOVIES_FAIL",

}